AllCops:
  Exclude:
    - '*.gemspec'
    - 'vendor/bundle/**/*'
Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
Style/Documentation:
  Exclude:
    - 'lib/lazy_ant/config.rb'
    - 'lib/lazy_ant/dsl.rb'
    - 'lib/lazy_ant/dsl/configurable.rb'
    - 'lib/lazy_ant/dsl/connection.rb'
    - 'lib/lazy_ant/dsl/endpoint.rb'
    - 'lib/lazy_ant/dsl/grouping.rb'
    - 'lib/lazy_ant/group.rb'
    - 'lib/lazy_ant/version.rb'
    - 'spec/**/*'
